#!/bin/bash

# Ez - IoT raspberry client installation script
# This is an installation script for the simulator, installing the proper dependencies when needed

# Install dependencies
echo "Installing dependencies..."
sudo apt-get --asume-yes install git
sudo apt-get --asume-yes install mosquitto-clients

# Git clone and create .config/ezsim
git clone https://github.com/Ez-IoT-Organization/EzIoT-backend.git
mkdir ~/.config/ezrasp

# Copy script files to .config/ezsim folder
cp EzIoT-backend/SoundSim/addNum.py EzIoT-backend/SoundSim/check.py EzIoT-backend/RaspImp/distance.py ~/.config/ezrasp

# Move to /usr/local/bin the SoundPub file 
sudo mv EzIoT-backend/RaspImp/PublishSensorData /usr/local/bin && sudo chmod +x /usr/local/bin/PublishSensorData

# Remove extra
echo "Installation completed! Deleting unneccesary folders..."
rm -rf EzIoT-backend/
