#!/bin/bash


############################################################################################################
#                                           Wrapper Script						   #
############################################################################################################
# Script functions

Help() # Help function
{
	echo "Usage: PubSound [OPTIONS] ... [FILE] ..."
        echo
        echo "Simulates a trash can and publishes data into a remote machine. Adittionally, the ssimulation stops if the trash can reaches its full capacity, or the user interrupts it."
        echo
        echo "Options for publishing the random data."
        echo "  -t, --time-inverval     time that it takes to send the data. Default will be 30 seconds."
        echo "  -c, --credentials       file of credentials for the remote machine"
        echo
        echo "  -h, --help              shows this help menu and exit"
        echo "  -v, --version           displays current version of script"
}

Extract_credentials()
{
        ip=$(sed '1q;d' $credentials)
	publisher=$(sed '2q;d' $credentials)
}

main()
{

	if [[ $credentials > 1 ]]; then
		test -f /tmp/PubSound.tmp
		if [ $? -eq 0 ]; then
			credentials=/tmp/PubSound.tmp 
		else
			cp $credentials /tmp/PubSound.tmp
			Extract_credentials
		fi

	fi

	accSum=1
	while true
	do

		cF=$(python3 ~/.config/ezsim/check.py $accSum)
		[[ $cF == "done" ]] && break

		echo "Sensor reading: $accSum"

		# Publish data to server using mqtt
		mosquitto_pub -h $ip -t Sensor -m "$publisher,$accSum"

		# Gen random number between 0.1 and 0.2 (3 decimals)
		rand=$(python3 ~/.config/ezsim/randNum.py)

		# Add random number to accSum var
		accSum=$(python3 ~/.config/ezsim/addNum.py $rand $accSum)

		sleep $time
	done

	mosquitto_pub -h $ip -t "Sensor" -m "$publisher,0"
	echo "The trash is full!"
	exit 0
}
options=$(getopt -o "t:c:i:p:vh" -l "time:,credentials:,ip:,publisher:version,help" -- "$@" )

if [ -z $@ 2>/dev/null ]; then
        echo "Missing arguments. Try PubSound -h or PubSound --help for more information." ; exit 1
fi

eval set -- "$options"
while true; do
	echo $otions
        case $1 in
                -c | --credentials) credentials=$2; shift 2;;
                -t | --time) time=$2; shift 2;;
		-p | --publisher) publisher=$2; shift 2;;
		-i | --ip) ip=$2; shift 2;;
                -h | --help) Help; exit 1;;
                -v | --version) echo "1.0.1"; exit 1;;
                --) shift; break;;
                *) echo "Invalid option. Try PubSound -h or PubSound --help for more information." ; exit 1;;
        esac
done

# 0(true) if time is empty
[ -z $time ] && time=30

# If no credentials passed but tmp exist
[ -z $credentials ] && test -f /tmp/PubSound.tmp && main
# If any credential missing
[ -z $ip ] || [ -z $publisher ] && echo "Any of the credentials missing. Try PubSound -h or PubSound --help for more information." && exit 1

# If credentials exist
main
